apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openwebui-loaders
  labels:
    app: openwebui-loaders
spec:
  to:
    kind: Service
    name: openwebui-loaders
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
