apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pypdf-extractor
  labels:
    app: pypdf-extractor
spec:
  to:
    kind: Service
    name: pypdf-extractor
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
