apiVersion: v1
kind: Service
metadata:
  name: openwebui-loaders
  labels:
    app: openwebui-loaders
    app.kubernetes.io/name: openwebui-loaders
    app.kubernetes.io/component: openwebui-loaders
spec:
  selector:
    app: openwebui-loaders
  ports:
    - name: http
      port: 80
      targetPort: 5001
      protocol: TCP
